In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set()

In [4]:
a = np.arange(1, 101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [8]:
b = np.arange(501, 601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

In [9]:
a_train, a_test, b_train, b_test = train_test_split(a, b, random_state=25)

In [10]:
a_train

array([ 22,  55,  78,  25,  68,  13,  36,  97,  94,   8,  86,  95,  59,
        43,  15,  18,  69,  20,  21,  27,  57,  54,  12,  84,  79,  71,
         6,   3,  53,  39,  77,  44,  41,  38,  31,  35,  72,  98,  19,
        50,  80,  76,  61,  11,  33,  10,  37,  93,  17,  74,  48,  49,
        89,  23,  87,  83,  46,  85,  56,   4,  40,   2,  70,  32, 100,
        29,   9,  51,  45,  24,  62,  16,  91,  63,   5])

In [11]:
a_test

array([42, 30, 34, 66, 75,  7, 58, 90, 88, 99,  1, 65, 82, 73, 67, 92, 96,
       64, 60, 47, 81, 26, 28, 14, 52])